### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by netzverweigerer** [ibabushkin/gabelstaplerwm#40]
Mind including a screenshot in the README so a possible newcomer gets a clue what to expect?

**Comment by ibabushkin** [comment]
I could do it, but to be honest, we're quite light on the graphical side. All the window manager itself does is drawing windows with thin borders. A bar, notifications, etc. are provided by external programs. But I guess I can add a screenshot with a more detailed explanation of what is shown and how to reproduce it yourself.
